version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - pipfile-v1-{{ checksum "Pipfile.lock" }}
            - pipfile-v1-
      - run: pipenv install --dev
      - save_cache:
          key: pipfile-v1-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - run: pipenv run python setup.py test


workflows:
  version: 2
  commit:
    jobs:
      - build
