version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - requirements-v1-{{ checksum "requirements.txt" }}
            - requirements-v1-
      - run: |
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - save_cache:
          key: requirements-v1-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run: |
          source venv/bin/activate
          python setup.py test

workflows:
  version: 2
  commit:
    jobs:
      - build
