---
name: Check harvest source duplicates

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  check_harvest_source_duplicates:
    name: Check Harvest Source Duplicates
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with: { python-version: 3.8 }
      - name: Install pip and pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: build
        run: pipenv sync
      - name: run check
        run: >
          pipenv run python duplicate-packages-organization.py
          --harvest_sources
          --run-id=test
      - name: save file
        uses: actions/upload-artifact@v3
        with:
          name: harvest_overview
          path: harvest-duplicates-test.csv
